# Generated by Django 5.2.3 on 2025-08-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskdetails_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
