# Generated by Django 5.2.3 on 2025-08-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_delete_employee_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_assets/default-image.png', null=True, upload_to='task_assets/'),
        ),
    ]
