# Generated by Django 5.2.3 on 2025-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='task_assets/default-image.png', null=True, upload_to='task_assets/'),
        ),
    ]
